### ISSUE TITLE
[Illuminate\Database\QueryException]

### ISSUE THREAD

**Issue by gwa99a9** [Stormyy/b3cod4x-standalone#1]
C:\xampp\htdocs\b3cod4x-standalone>php artisan migrate

  [Illuminate\Database\QueryException]
  could not find driver (SQL: select * from information_schema.tables where table_schema = ssdd2 and table_name = migrations)

  [Doctrine\DBAL\Driver\PDOException]
  could not find driver

  [PDOException]
  could not find driver

**Comment by Stormyy** [comment]
See

https://cod4x.me/index.php?/forums/topic/1428-b3-cod4x-screenshot-management-system/&do=findComment&comment=9243
